Ashraful_MVCProject/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;



using Ashraful_MVCProject.Models;

namespace Ashraful_MVCProject.Controllers
{
    [RoutePrefix("Information")]
    public class BookController : Controller
    {
        private Ashraful_MVCProjectEntities db = new Ashraful_MVCProjectEntities();

        [Authorize(Roles = "Admin")]

        [Route("List")]
        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.Author).Include(b => b.Publisher);

            ViewBag.Author = new SelectList(GetAuthorList(), "AuthorID", "AuthorName");
            ViewBag.Publisher = new SelectList(GetPublisherList(), "PublisherID", "PublisherName");


            return View(books.ToList());
        }

        public List<Author> GetAuthorList()
        {

            Ashraful_MVCProjectEntities db = new Ashraful_MVCProjectEntities();

            List<Author> authors = db.Authors.ToList();

            return authors;
        }

        public List<Publisher> GetPublisherList()
        {

            Ashraful_MVCProjectEntities db = new Ashraful_MVCProjectEntities();

            List<Publisher> publishers = db.Publishers.ToList();

            return publishers;
        }
        [Authorize(Roles = "Admin")]


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        [Authorize(Roles = "Admin")]

        public ActionResult Create()
        {
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "AuthorName");
            ViewBag.PublisherID = new SelectList(db.Publishers, "PublisherID", "PublisherName");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookID,BookName,BookPrice,BookEdition,Description,AuthorID,PublisherID")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "AuthorName", book.AuthorID);
            ViewBag.PublisherID = new SelectList(db.Publishers, "PublisherID", "PublisherName", book.PublisherID);
            return View(book);
        }

        [Authorize(Roles = "Admin")]

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "AuthorName", book.AuthorID);
            ViewBag.PublisherID = new SelectList(db.Publishers, "PublisherID", "PublisherName", book.PublisherID);
            return View(book);
        }

        [Authorize(Roles = "Admin")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookID,BookName,BookPrice,BookEdition,Description,AuthorID,PublisherID")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "AuthorName", book.AuthorID);
            ViewBag.PublisherID = new SelectList(db.Publishers, "PublisherID", "PublisherName", book.PublisherID);
            return View(book);
        }
        [Authorize(Roles = "Admin")]

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ashraful_MVCProject/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Ashraful_MVCProject.Models;
using System.Data.Entity;
using System.Net.Mail;
using System.Net;

namespace Ashraful_MVCProject.Controllers
{

    public class CustomerController : Controller
    {
        private Ashraful_MVCProjectEntities db = new Ashraful_MVCProjectEntities();


        public ActionResult Index()
        {
            ViewBag.CountryList = new SelectList(GetCountryList(), "CountryID", "CountryName");

            return View();
        }

        public List<Country> GetCountryList()
        {

            Ashraful_MVCProjectEntities db = new Ashraful_MVCProjectEntities();

            List<Country> countries = db.Countries.ToList();

            return countries;
        }

        public ActionResult GetStateList(int CountryId)
        {
            Ashraful_MVCProjectEntities db = new Ashraful_MVCProjectEntities();

            List<State> stateList = db.States.Where(x => x.CountryID == CountryId).ToList();

            ViewBag.StateOptions = new SelectList(stateList, "StateID", "StateName");

            return PartialView("StateOptionPartial");
        }

        public ActionResult GetCityList(int stateId)
        {
            Ashraful_MVCProjectEntities db = new Ashraful_MVCProjectEntities();

            List<City> cityList = db.Cities.Where(x => x.StateID == stateId).ToList();

            ViewBag.CityOptions = new SelectList(cityList, "CityID", "CityName");

            return PartialView("CityOptionPartial");

        }

        public ActionResult Create()
        {
            ViewBag.CountryList = new SelectList(GetCountryList(), "CountryID", "CountryName");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerRegistraion customerRegistraion)
        {
            ViewBag.CountryList = new SelectList(GetCountryList(), "CountryID", "CountryName");

            if (ModelState.IsValid)
            {
                db.CustomerRegistraions.Add(customerRegistraion);
                db.SaveChanges();

                //Send to Customer

                MailMessage m = new MailMessage(new MailAddress("reapon.test@gmail.com", "Customer Registration"), new MailAddress(customerRegistraion.Email));

                m.Subject = "Registration";
                m.Body = string.Format("Dear {0}, Thank You For Your Registration. <BR/> Now You Can enjoy all facilities of our online Library!!", customerRegistraion.CustomerName);

                m.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient("smtp.gmail.com");
                smtp.Credentials = new NetworkCredential("reapon.test@gmail.com", "01828074472");
                smtp.EnableSsl = true;
                smtp.Send(m);

                //Send To Authority

                MailMessage mail = new MailMessage(new MailAddress("reapon.test@gmail.com", "Customer Registration Info"), new MailAddress("reapon.test@gmail.com"));

                mail.Subject = "New Customer Registration";
                mail.Body = string.Format("{0} Has Been Registered. <BR/> Some of his/her Information are given below: <BR/> Email : {1} <BR/> Phone : {2} <BR/>", customerRegistraion.CustomerName, customerRegistraion.Email, customerRegistraion.Phone);
                mail.IsBodyHtml = true;
                smtp.Send(mail);

                return RedirectToAction("Success");
            }
            return View();
        }



        public ActionResult Success()
        {
            return View();
        }

    }
}

Ashraful_MVCProject/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Ashraful_MVCProject.Models;
using System.Data.Entity;

namespace Ashraful_MVCProject.Controllers
{
    public class RolesController : Controller
    {
        [Authorize(Roles ="Admin")]
        public ActionResult Start()
        {
            return View();
        }


        // GET: Roles
        [Authorize(Roles ="Admin")]
        public ActionResult Index()
        {
            //Populate dropdown list
            var context = new ApplicationDbContext();

            var roleList = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = roleList;

            var userList = context.Users.OrderBy(u => u.UserName).ToList().Select(uu => new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();

            ViewBag.Users = userList;

            ViewBag.Message = "";
            return View();
        }

        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var context = new ApplicationDbContext();
                context.Roles.Add(new IdentityRole() { Name = collection["RoleName"] });
                context.SaveChanges();
                ViewBag.Message = "Role Created Successfully";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles ="Admin")]
        public ActionResult Delete(string roleName)
        {
            var context = new ApplicationDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles ="Admin")]
        public ActionResult Edit(string roleName)
        {
            var context = new ApplicationDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            return View(thisRole);
        }
        [Authorize(Roles ="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IdentityRole role)
        {
            try
            {
                var context = new ApplicationDbContext();
                context.Entry(role).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]

        public ActionResult RoleAddToUser(string userName, string roleName)
        {
            var context = new ApplicationDbContext();
            if (context == null)
            {
                throw new ArgumentNullException("context", "Context must not be null!!");
            }
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(userName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);
            userManager.AddToRole(user.Id, roleName);

            ViewBag.Message = "Role Assigned Successfully";


            // Populate DropdownList
            var roleList = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
              new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = roleList;

            var userList = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
              new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userList;

            return View("Index");

        }

        // Getting a list of Roles for user
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]

        public ActionResult GetRoles(string userName)
        {
            if (!string.IsNullOrWhiteSpace(userName))
            {
                var context = new ApplicationDbContext();
                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(userName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

                var userStore = new UserStore<ApplicationUser>(context);
                var userManager = new UserManager<ApplicationUser>(userStore);

                ViewBag.RolesForThisUser = userManager.GetRoles(user.Id);
                // Populate DropdownList
                var roleList = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
                  new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                ViewBag.Roles = roleList;

                var userList = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
                  new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
                ViewBag.Users = userList;

                ViewBag.Message = "Role Retrieved Successfully!!!";

            }
            return View("Index");
        }

        [Authorize(Roles ="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string userName, string roleName)
        {
            var account = new AccountController();
            var context = new ApplicationDbContext();

            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(userName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);

            if (userManager.IsInRole(user.Id, roleName))
            {
                userManager.RemoveFromRole(user.Id, roleName);
                ViewBag.Message = "Role removed from this user successfully";
            }
            else
            {
                ViewBag.Message= "This user doesn't belong to selected role!!!!";
            }

            // Populate DropdownList
            var roleList = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
              new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = roleList;

            var userList = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
              new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userList;

            return View("Index");

        }








    }
}

Ashraful_MVCProject/Views/Shared/CityOptionPartial.cshtml
<option value="">--Select City--</option>
@if (ViewBag.CityOptions != null)
{

    foreach (var item in ViewBag.CityOptions)
    {

        <option value="@item.Value">@item.Text </option>

    }

}

Ashraful_MVCProject/Views/Shared/StateOptionPartial.cshtml
<option value="">--Select State--</option>
@if (ViewBag.StateOptions != null)
{

    foreach (var item in ViewBag.StateOptions)
    {

        <option value="@item.Value">@item.Text </option>

    }

}

Ashraful_MVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Max E-Library</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    @*<link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>*@

    @*<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Max E-Library", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Customer Registration", "Create", "Customer")</li>

                    <li>@Html.ActionLink("Admin Panel", "Start", "Roles")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @*<script src="~/Scripts/Scripts.js"></script>
    <script src="~/Scripts/notify.min.js"></script>


    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>*@
</body>
</html>

Ashraful_MVCProject/Views/Shared/_LayoutForAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Admin Panel</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#d0e8f2;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Admin Panel", "Start", "Roles", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Role Manage", "Index", "Roles")</li>
                    <li>@Html.ActionLink("Publisher", "Index", "Publisher")</li>
                    <li>@Html.ActionLink("Book Information", "Index", "Book")</li>
                    <li>@Html.ActionLink("Author", "Index", "TestAuthor")</li>
                    <li>@Html.ActionLink("Supplier", "Index", "Supplier")</li>

                    <li>@Html.ActionLink("Custom Attribute", "Index", "CustomAuthor")</li>

                    <li>@Html.ActionLink("Back To Home", "Index", "Home")</li>



                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Max E-Library Admin Panel</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/Scripts.js"></script>
    <script src="~/Scripts/notify.min.js"></script>
</body>
</html>